apiVersion: v1
kind: Pod
metadata:
  name: agent
  namespace: fais-1
spec:
  securityContext:
    runAsUser: 270999
    runAsGroup: 1132
  containers:
    - name: agent-pod
      image: 'ghcr.io/stmorse/agent-mini-agent:latest'
      resources:
        requests:
          memory: '4Gi'
          cpu: '1'
      command: ['/bin/sh', '-c', 'sleep infinity']
      volumeMounts:
        - name: home
          mountPath: /home
  volumes:
    - name: home
      nfs:
        server: 128.239.56.166
        path: /sciclone/home/stmorse
