apiVersion: apps/v1
kind: Deployment
metadata:
  name: faiss
  namespace: fais-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faiss
  template:
    metadata:
      labels:
        app: faiss
    spec:
      securityContext:
        runAsUser: 270999
      containers:
      - name: faiss-container
        image: ghcr.io/stmorse/agent-mini-faiss:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: '1Gi'
            nvidia.com/gpu: '1'
          limits:
            memory: '1Gi'
            nvidia.com/gpu: '1'
        command: ['/bin/sh', '-c', 'sleep infinity']
        volumeMounts:
        - name: home
          mountPath: /sciclone/home/stmorse
      volumes:
      - name: home
        nfs:
          server: 128.239.56.166
          path: /sciclone/home/stmorse
---
apiVersion: v1
kind: Service
metadata:
  name: faiss
  namespace: fais-1
spec:
  selector:
    app: faiss
  ports:
    - protocol: TCP
      port: 90
      targetPort: 5000
  type: ClusterIP
