apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: fais-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      securityContext:
        runAsUser: 27099
        runAsGroup: 1132
        fsGroup: 1132
      # initContainers:
      # - name: copy-db
      #   image: ubuntu  # minimal image to support copying
      #   command: ["/bin/bash", "-c", "cp -r /mnt/db/* /var/lib/postgresql/data/"]
      #   volumeMounts:
      #   - name: postgres-nfs-storage
      #     mountPath: /mnt/db
      #   - name: postgres-data
      #     mountPath: /var/lib/postgresql/data
      containers:
      - name: postgres
        image: ghcr.io/stmorse/agent-mini-postgres:latest
        resources:
          requests:
            memory: "4Gi"
            cpu: "1"
          limits:
            memory: "4Gi"
            cpu: "1"
        env:
        - name: POSTGRES_DB
          value: "mydb"
        - name: POSTGRES_USER
          value: "user"
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
        # volumeMounts:
        # - name: postgres-nfs-storage
        #   mountPath: /var/lib/postgresql/data
      # volumes:
      # # - name: postgres-data
      # #   emptyDir: {}    # ephemeral postgres data storage
      # - name: postgres-nfs-storage
      #   nfs:
      #     server: 128.239.56.166
      #     path: /sciclone/home/stmorse/projects/fais/db
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: fais-1
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  # type: ClusterIP
