name: Agent Image Build

on: push

env:
  REPO_OWNER: stmorse

jobs:

  build:

    runs-on: ubuntu-latest
    permissions: read-all|write-all
      # contents: read
      # packages: write
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}   
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./dockerfiles/agent/Dockerfile
        push: true
        tags: ghcr.io/${{ env.REPO_OWNER }}/agent:latest
